### ISSUE TITLE
Decompression can panic on malformed input

### ISSUE THREAD

**Issue by floriankramer** [laz-rs/laz-rs#43]
Reading an laz file can fail on some inputs. I'm still working on figuring out what about the input is the issue. As it contains customer data I can sadly not provide the laz file that triggers the panic.

```
thread 'main' panicked at 'attempt to divide by zero', /home/_/.cargo/registry/src/github.com-1ecc6299db9ec823/laz-0.7.0/src/decoders.rs:162:22
stack backtrace:
   0: rust_begin_unwind
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:579:5
   1: core::panicking::panic_fmt
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:64:14
   2: core::panicking::panic
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:114:5
   3: laz::decoders::ArithmeticDecoder<T>::decode_symbol
   4: <laz::las::point6::v3::LasPoint6Decompressor as laz::record::LayeredFieldDecompressor<R>>::decompress_field_with
   5: <laz::record::LayeredPointRecordDecompressor<R> as laz::record::RecordDecompressor<R>>::decompress_next
   6: laz::laszip::decompression::LasZipDecompressor<R>::decompress_one
   7: <las::compression::CompressedPointReader<R> as las::reader::PointReader>::read_next
   8: <las::reader::PointIterator as core::iter::traits::iterator::Iterator>::next
   9: load_laz::main
```

**Comment by floriankramer** [comment]
After some reading into how arithmetic encoding works I gave up on tracing the exact issue with the file. If you are willing to spare some more instructions 0 checks before the division (which rust apparently does anyways to check for division by 0) might be the simplest way of turning this from a panic into an error. Given the high cost of integer division and the (relatively) low cost of an easy to predict branch it could be worth adding checks.
